const NOT_STARTED = "NOT_STARTED";
const GENERATING_ACCOUNT = "GENERATING_ACCOUNT";
const FUNDING_WITH_ETH = "FUNDING_WITH_ETH";
const FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE =
  "FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE";
const FUNDING_WITH_MANA = "FUNDING_WITH_MANA";
const APPROVING_MARKETPLACE = "APPROVING_MARKETPLACE";
const READY_TO_USE = "READY_TO_USE";

export default {
  NOT_STARTED,
  GENERATING_ACCOUNT,
  FUNDING_WITH_ETH,
  FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE,
  FUNDING_WITH_MANA,
  APPROVING_MARKETPLACE,
  READY_TO_USE,
};
