export const NOT_STARTED = "NOT_STARTED";
export const GENERATING_ACCOUNT = "GENERATING_ACCOUNT";
export const FUNDING_WITH_ETH = "FUNDING_WITH_ETH";
export const FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE =
  "FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE";
export const FUNDING_WITH_MANA = "FUNDING_WITH_MANA";
export const APPROVING_MARKETPLACE = "APPROVING_MARKETPLACE";
export const READY_TO_USE = "READY_TO_USE";

export default {
  NOT_STARTED,
  GENERATING_ACCOUNT,
  FUNDING_WITH_ETH,
  FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE,
  FUNDING_WITH_MANA,
  APPROVING_MARKETPLACE,
  READY_TO_USE,
};
