export enum AccountCreationStatusType {
  NOT_STARTED = "NOT_STARTED",
  GENERATING_ACCOUNT = "GENERATING_ACCOUNT",
  FUNDING_WITH_ETH = "FUNDING_WITH_ETH",
  FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE = "FUNDING_WITH_MANA_AND_APPROVING_MARKETPLACE",
  FUNDING_WITH_MANA = "FUNDING_WITH_MANA",
  APPROVING_MARKETPLACE = "APPROVING_MARKETPLACE",
  READY_TO_USE = "READY_TO_USE",
}
